# Goal
folding_assembly_controller/AdaptiveController adaptive_params
bool use_pose_goal
float64 theta_lim
float64 max_contact_force
folding_assembly_controller/PoseGoal pose_goal
folding_assembly_controller/VelocityGoal velocity_goal
---
# Result
---
# Feedback
