# Goal
folding_assembly_controller/AdaptiveController adaptive_params
bool use_pose_goal
folding_assembly_controller/PoseGoal pose_goal
folding_assembly_controller/VelocityGoal velocity_goal
---
# Result
---
# Feedback
string phase
float64 force_norm
geometry_msgs/WrenchStamped wrench_total
geometry_msgs/WrenchStamped wrench_compensated_1
geometry_msgs/WrenchStamped wrench_compensated_2
geometry_msgs/PointStamped contact_point_ground
geometry_msgs/PointStamped contact_point_estimated
geometry_msgs/PointStamped p1
geometry_msgs/PointStamped p2
geometry_msgs/Vector3Stamped t
geometry_msgs/Vector3Stamped k
geometry_msgs/Vector3Stamped n
