geometry_msgs/Twist desired_velocities # Uses linear.x and angular.z respectively for desired sliding and rotational velocities
---
float64 elapsed_time 
---
geometry_msgs/Twist commanded_velocities # This is the output to the robot eef
